export const projects = [
  {
    title: "MERN Memories",
    image: "https://picsum.photos/id/100/200",
    tags: ["Mongo", "Express", "React", "Node"],
    source: "https://google.com",
    category: "Featured",
    visit: "https://google.com",
    id: 0,
  },
  {
    title: "E-Commerce",
    image: "https://picsum.photos/id/238/200",
    tags: ["React", "JavaScript"],
    category: "DSC Projects",
    source: "https://google.com",
    visit: "https://google.com",
    id: 1,
  },
  {
    title: "WebRTC App",
    image: "https://picsum.photos/id/239/200",
    tags: ["React", "WebRTC"],
    category: "DSC Projects",
    source: "https://google.com",
    visit: "https://google.com",
    id: 2,
  },
  {
    title: "E-Commerce",
    image: "https://picsum.photos/id/228/200",
    tags: ["React", "JavaScript"],
    category: "Featured",
    source: "https://google.com",
    visit: "https://google.com",
    id: 3,
  },
  {
    title: "WebRTC App",
    image: "https://picsum.photos/id/210/200",
    tags: ["React", "WebRTC"],
    category: "Featured",
    source: "https://google.com",
    visit: "https://google.com",
    id: 4,
  },
  {
    title: "E-Commerce",
    image: "https://picsum.photos/id/250/200",
    tags: ["React", "JavaScript"],
    category: "DSC Projects",
    source: "https://google.com",
    visit: "https://google.com",
    id: 5,
  },
];
