export const projects = [
  {
    title: "MERN Memories",
    image: "https://picsum.photos/id/100/200",
    tags: ["Mongo", "Express", "React", "Node"],
    source: "https://google.com",
    category: "Featured",
    visit: "https://google.com",
    id: 0,
  },
  {
    title: "E-Commerce",
    image: "https://picsum.photos/id/238/200",
    tags: ["React", "JavaScript"],
    category: "DSC Projects",
    source: "https://google.com",
    visit: "https://google.com",
    id: 1,
  },
  {
    title: "WebRTC App",
    image: "https://picsum.photos/id/239/200",
    tags: ["React", "WebRTC"],
    category: "DSC Projects",
    source: "https://google.com",
    visit: "https://google.com",
    id: 2,
  },
  {
    title: "E-Commerce",
    image: "https://picsum.photos/id/228/200",
    tags: ["React", "JavaScript"],
    category: "Featured",
    source: "https://google.com",
    visit: "https://google.com",
    id: 3,
  },
  {
    title: "WebRTC App",
    image: "https://picsum.photos/id/210/200",
    tags: ["React", "WebRTC"],
    category: "Featured",
    source: "https://google.com",
    visit: "https://google.com",
    id: 4,
  },
  {
    title: "E-Commerce",
    image: "https://picsum.photos/id/250/200",
    tags: ["React", "JavaScript"],
    category: "DSC Projects",
    source: "https://google.com",
    visit: "https://google.com",
    id: 5,
  },
];

export const members = {
  "DSC Lead": {
    id: 0,
    name: "Unknown",
    designation: "Full-Stack Developer",
    image: "https://source.unsplash.com/featured/?man",
    quote: "Experience is the name everyone gives to their mistakes.",
    linkedin: "",
    github: "",
    instagram: "",
  },
  "Core Team": [
    {
      id: 1,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 2,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 3,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 4,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 5,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
  ],
  "Web Dev": [
    {
      id: 1,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 2,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 3,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
  ],
  "AI Team": [
    {
      id: 1,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 2,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 3,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
  ],
  "Non Tech": [
    {
      id: 1,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 2,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 3,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 4,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 5,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
    {
      id: 6,
      name: "Unknown",
      designation: "Full-Stack Developer",
      image: "https://source.unsplash.com/featured/?man",
      quote: "Experience is the name everyone gives to their mistakes.",
      linkedin: "",
      github: "",
      instagram: "",
    },
  ],
};
